name: flutterrecipeapp
description: A Flutter application which demostrate the BLoC pattern, API calling, Seperating business logic from widget, clean code, and pagination 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  # A Flutter package that helps implement the BLoC pattern.
  flutter_bloc: ^4.0.0
  # Simplify Equality Comparisons
  equatable: ^1.2.0
  # A composable, Future-based library for making HTTP requests.
  http: ^0.12.1
  mockito: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true